require("plugins_config.gruvbox")
require("plugins_config.lualine")
require("plugins_config.nvim-tree")
require("plugins_config.treesitter")
require("plugins_config.telescope")
require("plugins_config.lsp")
require("plugins_config.copilot")
